# Generated by Django 3.1 on 2020-08-17 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_name', models.CharField(max_length=255, null=True)),
                ('est_traffic', models.FloatField(blank=True, null=True)),
                ('avg_position', models.FloatField(blank=True, null=True)),
                ('backlinks', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=9999999, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('top_rank', models.IntegerField(blank=True, null=True)),
                ('competitor_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('competitor_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('indexed_pages', models.IntegerField(blank=True, null=True)),
                ('site_map', models.CharField(blank=True, max_length=255, null=True)),
                ('page_load_time', models.IntegerField(blank=True, null=True)),
                ('ssl_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('back_links', models.IntegerField(blank=True, null=True)),
                ('outbound_links', models.IntegerField(blank=True, null=True)),
                ('broken_links', models.IntegerField(blank=True, null=True)),
                ('organic_search_traffic', models.IntegerField(blank=True, null=True)),
                ('mobile_responsiveness', models.CharField(blank=True, max_length=255, null=True)),
                ('competitor_page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('competitor_indexed_pages', models.IntegerField(blank=True, null=True)),
                ('competitor_site_map', models.CharField(blank=True, max_length=255, null=True)),
                ('competitor_page_load_time', models.IntegerField(blank=True, null=True)),
                ('competitor_ssl_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('competitor_back_links', models.IntegerField(blank=True, null=True)),
                ('competitor_outbound_links', models.IntegerField(blank=True, null=True)),
                ('competitor_broken_links', models.IntegerField(blank=True, null=True)),
                ('competitor_organic_search_traffic', models.IntegerField(blank=True, null=True)),
                ('competitor_mobile_responsiveness', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.campaign')),
            ],
        ),
    ]
