# Generated by Django 3.1 on 2020-08-13 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_traffic', models.FloatField(blank=True, null=True)),
                ('avg_position', models.FloatField(blank=True, null=True)),
                ('backlinks', models.FloatField(blank=True, null=True)),
                ('campaign', models.ManyToManyField(to='api.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('campaign', models.ManyToManyField(to='api.Campaign')),
                ('site', models.ManyToManyField(to='api.Site')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('top_rank', models.IntegerField()),
                ('trend', models.ImageField(upload_to='trend/')),
                ('competitor_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('competitor_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('details', models.ManyToManyField(to='api.Keywords')),
            ],
        ),
    ]
