# Generated by Django 3.1 on 2020-08-14 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyworddetails',
            name='competitor_one',
        ),
        migrations.RemoveField(
            model_name='keyworddetails',
            name='details',
        ),
        migrations.RemoveField(
            model_name='keyworddetails',
            name='trend',
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='site',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keyworddetails',
            name='keyword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.keywords'),
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='campaign',
        ),
        migrations.AddField(
            model_name='keywords',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.campaign'),
        ),
        migrations.RemoveField(
            model_name='site',
            name='campaign',
        ),
        migrations.AddField(
            model_name='site',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.campaign'),
        ),
        migrations.CreateModel(
            name='CompareCompetitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor', models.CharField(max_length=255, null=True)),
                ('page_title', models.CharField(max_length=255, null=True)),
                ('indexed_pages', models.IntegerField()),
                ('site_map', models.CharField(max_length=255, null=True)),
                ('page_load_time', models.IntegerField()),
                ('ssl_certificate', models.CharField(max_length=255, null=True)),
                ('back_links', models.IntegerField()),
                ('outbound_links', models.IntegerField()),
                ('broken_links', models.IntegerField()),
                ('organic_search_traffic', models.IntegerField()),
                ('mobile_responsiveness', models.CharField(max_length=255, null=True)),
                ('competitor_page_title', models.CharField(max_length=255, null=True)),
                ('competitor_indexed_pages', models.IntegerField()),
                ('competitor_site_map', models.CharField(max_length=255, null=True)),
                ('competitor_page_load_time', models.IntegerField()),
                ('competitor_ssl_certificate', models.CharField(max_length=255, null=True)),
                ('competitor_back_links', models.IntegerField()),
                ('competitor_outbound_links', models.IntegerField()),
                ('competitor_broken_links', models.IntegerField()),
                ('competitor_organic_search_traffic', models.IntegerField()),
                ('competitor_mobile_responsiveness', models.CharField(max_length=255, null=True)),
                ('time', models.IntegerField()),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.keywords')),
            ],
        ),
    ]
