# Generated by Django 3.1 on 2020-08-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200814_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyworddetails',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='site',
            name='campaign',
        ),
        migrations.AddField(
            model_name='campaign',
            name='avg_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='backlinks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='est_traffic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='back_links',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='broken_links',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_back_links',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_broken_links',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_indexed_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_mobile_responsiveness',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_one',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_organic_search_traffic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_outbound_links',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_page_load_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_site_map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_ssl_certificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_two',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='indexed_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='mobile_responsiveness',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='organic_search_traffic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='outbound_links',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='page_load_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='site_map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='ssl_certificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='top_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CompareCompetitor',
        ),
        migrations.DeleteModel(
            name='KeywordDetails',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
