# Generated by Django 3.1 on 2020-08-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200807_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_traffic', models.FloatField(blank=True, null=True)),
                ('avg_position', models.FloatField(blank=True, null=True)),
                ('backlinks', models.FloatField(blank=True, null=True)),
                ('campaign', models.ManyToManyField(to='api.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('campaign', models.ManyToManyField(to='api.Campaign')),
                ('site', models.ManyToManyField(to='api.Site')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('top_rank', models.IntegerField()),
                ('trend', models.ImageField(upload_to='trend/')),
                ('competitor_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('competitor_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('details', models.ManyToManyField(to='api.Keywords')),
            ],
        ),
    ]
