# Generated by Django 3.1 on 2020-08-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='competitor_page_load_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='page_load_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
