# Generated by Django 3.1 on 2020-08-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200829_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='time',
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='rank_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
