# Generated by Django 3.1 on 2020-08-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200829_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='average_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='average_position_percentage_increase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='avp_data_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='keyword_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='keyword_count_percentage_increase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='kwc_data_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='kwc_update_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='rank_data_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
