# Generated by Django 3.1 on 2020-09-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200831_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='competitor_site_map_testtime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='site_map_testtime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
