# Generated by Django 3.1 on 2020-09-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200901_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='indexed_pages',
        ),
        migrations.AddField(
            model_name='campaign',
            name='indexed_check_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='indexed_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='competitor_indexed_check_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
